### ISSUE TITLE
Uncaught exception 'SpotifyWebAPI\SpotifyWebAPIException'

### ISSUE THREAD

**Issue by AudricManaud** [jwilsson/spotify-web-api-php#32] opened 2015-04-30 22:20 UTC
Hello,

I think I'm having the same issue that https://github.com/jwilsson/spotify-web-api-php/issues/29.
Here's my error: <a href="http://www.noelshack.com/2015-18-1430432140-spotify-error.png"><img src="http://image.noelshack.com/minis/2015/18/1430432140-spotify-error.png" border="0" alt="1430432140-spotify-error.png - envoi d'image avec NoelShack" title="1430432140-spotify-error.png"/></a>

So, when I launch index.php it asks me the authorization and when I say 'yes' I'm getting this.
I have an another page callback.php which is called once the user clicks on 'yes'.
These two pages only contain the code provided by you.
I tried to run it on both Linux and Windows :)

If you need anything, ask me !
Thanks in advance, it's really important for me to solve this problem :+1: 

Audric.

**Comment by jwilsson** [comment] 2015-05-01 07:57
Some code is appreciated :)

**Comment by AudricManaud** [comment] 2015-05-01 09:31
Here it is :)
https://github.com/AudricManaud/SpotifyAPI

**Comment by jwilsson** [comment] 2015-05-01 10:33
Thanks!

I think your problem lies in a mismatch between the callback URI you've registered at Spotify and the one you're actually using.

In the screenshot, the URL seems to be `http://localhost/promus/callback.php` but in the code you posted, the redirect URI is `http://localhost/callback.php`. Try changing one of them, either the registered URI at Spotify or move the files so they're placed where Spotify expects them.

**Comment by AudricManaud** [comment] 2015-05-01 10:44
Owwh I'm sorry that's a previous screenshot, I corrected it and it's still doesn't work:
<a href="http://www.noelshack.com/2015-18-1430477028-spotify-error.png"><img src="http://image.noelshack.com/minis/2015/18/1430477028-spotify-error.png" border="0" alt="1430477028-spotify-error.png - envoi d'image avec NoelShack" title="1430477028-spotify-error.png"/></a>

**Comment by jwilsson** [comment] 2015-05-01 14:20
Alright, I've tried reproducing it but I can't find anything wrong with it.

Could you dump the whole response by adding something like 

    print_r($response) 

on line 126 of `Request.php`, right after the line

    curl_close($ch);

and post the result here.

**Comment by AudricManaud** [comment] 2015-05-01 14:26
Weird, it doesn't display anything at all...
<a href="http://www.noelshack.com/2015-18-1430490339-spotify.png"><img src="http://image.noelshack.com/minis/2015/18/1430490339-spotify.png" border="0" alt="1430490339-spotify.png - envoi d'image avec NoelShack" title="1430490339-spotify.png"/></a>

**Comment by jwilsson** [comment] 2015-05-01 14:28
Hmm, try with

    var_dump(curl_error($ch));

instead. But put it before the

    curl_close($ch);

line.

**Comment by AudricManaud** [comment] 2015-05-01 14:32
There it is:
<a href="http://www.noelshack.com/2015-18-1430490663-spotify-error.png"><img src="http://image.noelshack.com/minis/2015/18/1430490663-spotify-error.png" border="0" alt="1430490663-spotify-error.png - envoi d'image avec NoelShack" title="1430490663-spotify-error.png"/></a>

<a href="http://www.noelshack.com/2015-18-1430490663-sublime-text.png"><img src="http://image.noelshack.com/minis/2015/18/1430490663-sublime-text.png" border="0" alt="1430490663-sublime-text.png - envoi d'image avec NoelShack" title="1430490663-sublime-text.png"/></a>

I got teamviewer if you want too :)

**Comment by jwilsson** [comment] 2015-05-01 14:43
Great, thanks!

At least we found the problem, cURL needs a local bundle of root certificates. Take a look at this answer: https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/37017 and restart your local server and it should work.

I hope to get a better fix for this into the library.

**Comment by AudricManaud** [comment] 2015-05-01 14:56
Oh my god, it works thank you very much !
You've been so helpful to me :+1: 
If you need to run some tests on my computer to solve it for everyone, just contact me :)

Audric.

**Comment by jwilsson** [comment] 2015-05-01 15:09
Awesome!

Glad we figured it out :)

**Closed by jwilsson** 2015-05-01 15:10 UTC

**Comment by rubenvdb** [comment] 2015-06-12 16:07
Seemed to be solved at first, but now stopped working again.

**Comment by jwilsson** [comment] 2015-06-12 18:40
@rubenvdb Could you pull down the `0.9.0` branch, test with that code and then open a new issue with the error received.

Thanks!
